config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	root :to => "root#top"
	get '/top' => 'root#top', as: 'top'
	get '/about' => 'root#about', as: 'about'
	get '/home' => 'root#home', as: 'home'
	resources :users do
		member do
			get :following, :followers
		end
	end
	resources :posts do
		resource :comments, only: [:create, :destroy]
		resource :favorites, only: [:create, :destroy]
		resource :replies
	end
	resources :relationships, only: [:create, :destroy]
	get 'tags/:tag', to: 'posts#index', as: :tag
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user

	validates :comment_text, length: {maximum: 256} 
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	acts_as_taggable
	
	attachment :post_image
	attachment :post_sound
	
	has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	belongs_to :user
	has_many :replies, dependent: :destroy

	validates :post_title, length: {maximum: 128} 
	validates :post_text, length: {maximum: 256} 
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/reply.rb
class Reply < ApplicationRecord
	attachment :reply_image
	attachment :reply_sound
	
	belongs_to :post
	belongs_to :user

	validates :reply_title, length: {maximum: 128} 
	validates :reply_text, length: {maximum: 256} 

end

app/models/user.rb
class User < ApplicationRecord
	attachment :user_image
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :validatable

	has_many :favorites, dependent: :destroy
	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :replies, dependent: :destroy

	has_many :active_relationships, class_name: "Relationship",
									 foreign_key: "follower_id",
									 dependent: :destroy
	has_many :passive_relationships, class_name: "Relationship",
									 foreign_key: "followed_id",
									 dependent: :destroy
	has_many :following, through: :active_relationships, source: :followed
	has_many :followers, through: :passive_relationships

	validates :name, presence: true
	validates :email, uniqueness: true
	validates :profile, length: {maximum: 128} 

	# フォローする
	def follow(other_user)
    following << other_user
  	end

 	# フォロー解除する
	def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
	end

  	# 現在のユーザーがフォローしてたらtrueを返す
	def following?(other_user)
    following.include?(other_user)
	end

  	# 現在のユーザーにフォローされていたらtrueを返す
	def followers?(other_user)
	followers.include?(other_user)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_search

	def set_search
		@search = Post.ransack(params[:q])
		@search_posts = @search.result.order(created_at: :desc).includes(:user)
	end

	protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :current_user,only:[:edit,:update,:destroy]
	
	def create
		post = Post.find(params[:post_id])
		comment = current_user.comments.new(comment_params)
		comment.post_id = post.id
		comment.save
		redirect_to post_path(post.id)
	end

	private
	def comment_params
		params.require(:comment).permit(:user_id, :post_id, :comment_text)
	end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		post = Post.find(params[:post_id])
		favorite = current_user.favorites.new(post_id: post.id)
		favorite.save
		redirect_to post_path(post.id)
	end

	def destroy
		post = Post.find(params[:post_id])
		favorite = current_user.favorites.find_by(post_id: post.id)
		favorite.destroy
		redirect_to post_path(post.id)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user! 
	before_action :current_user,only:[:edit,:update,:destroy]

	def index
		@post = Post.new
		if params[:tag]
			@posts = Post.tagged_with(params[:tag])
		else
			@posts = Post.all.order(created_at: :desc)
		end
	end

	def create
		post = Post.new(post_params)
		post.user_id = current_user.id
		if post.save
			flash[:notice] = "投稿しました!"
			redirect_to post_path(post.id)
		else
			flash[:notice] = "Error!"
			render :index
		end
	end

	def show
		@post = Post.find(params[:id]) 
		@comment = Comment.new
		@reply = Reply.new
		@replies = @post.replies.order(created_at: :desc)
	end

	def edit
		@post = Post.find(params[:id]) 
	end

	def update
		@post = Post.find(params[:id]) 
		if @post.update(post_params)
			flash[:notice] = "更新しました!"
			redirect_to post_path(@post)
		else
			flash[:notice] = "Error!"
			render :show
		end
	end

	def destroy
		@post = Post.find(params[:id])
		if @post.destroy
			flash[:notice] = "消去しました!"
			redirect_to posts_path
		else
			flash[:notice] = "Error!"
			render :show
		end
	end

	private

	def post_params
		params.require(:post).permit(:post_title,:post_text,:post_image,:post_sound,:tag_list)
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
	before_action :current_user,only:[:edit,:update,:destroy]

	def create
		post = Post.find(params[:post_id])
		reply = current_user.replies.new(reply_params)
		reply.post_id = post.id
		if reply.save
			flash[:notice] = "投稿しました!"
			redirect_to post_path(post.id)
		else
			flash[:notice] = "Error!"
			render :show
		end
	end

	def edit
		@reply = Reply.find(params[:id])
	end

	def update
		@reply = Reply.find(params[:id])
		if @reply.update(reply_params)
			flash[:notice] = "更新しました!"
			redirect_to post_path(post.id)
		else
			flash[:notice] = "Error!"
			render :show
		end
	end

	def destroy
		@reply = Reply.find(params[:id])
		if @post.destroy
			flash[:notice] = "消去しました!"
			redirect_to posts_path
		else
			flash[:notice] = "Error!"
			render :show
		end
	end


	private
	def reply_params
		params.require(:reply).permit(:user_id, :post_id, :reply_title, :reply_text, :reply_image, :reply_sound)
	end

end

app/controllers/root_controller.rb
class RootController < ApplicationController
	before_action :authenticate_user!, only: [:home]

	def top
	end
	
	def about
	end

	def home
		@posts = Post.all.order(created_at: :desc)
		@users = User.all.order(created_at: :desc)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:index, :show, :edit, :update, :following, :followers]
	before_action :current_user,only:[:edit,:update,:destroy]

	def index
		@users = User.all.order(created_at: :desc)
	end

	def show
		@user = User.find(params[:id])
		@posts = @user.posts
		@favorites = @user.favorites
		@following = @user.following
		@followers = @user.followers
		@replies = @user.replies
	end

	def create
		@user = User.new(user.params) 
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = "ユーザー情報を更新しました!"
			redirect_to user_path(current_user.id)
		else
			flash[:notice] = "Error!"
			render :show
		end
	end

	private
	def user_params
		params.require(:user).permit(:name,:profile,:user_image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def date_format(datetime)
		time_ago_in_words(datetime) + 'ago'
	end
	
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_postmodal.html.erb
<div class="text-center" id="modal">
	<button type="button" class="btn btn-default mt-5 fas fa-tree" data-toggle="modal" data-target="#post">投稿する</button>
	<div class="modal fade" id="post" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<%= form_for(post) do |f| %>
				<div class="modal-body">
					<p>タイトル</p>
					<%= f.text_field :post_title, size: "70x1" %>
					<p>タグ</p>
					<%= f.text_field :tag_list, size: "70x1" %>
					<p>テキスト</p>
					<%= f.text_area :post_text, size: "70x8"  %>
					<p>画像</p>
					<%= f.attachment_field :post_image,class: "center-block" %>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
					<%= f.submit "投稿する", class: "btn btn-primary" %>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/posts/_replymodal.html.erb
<span class="text-center" id="modal">
	<button type="button" class="btn btn-default mt-5 fas fa-reply" data-toggle="modal" data-target="#reply">返信する</button>
	<div class="modal fade" id="reply" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<%= form_for [post, reply] do |f| %>
				<div class="modal-body">
					<p>タイトル</p>
					<%= f.text_field :reply_title, size: "70x1" %>
					<p>テキスト</p>
					<%= f.text_area :reply_text, size: "70x8" %>
					<p>画像</p>
					<%= f.attachment_field :reply_image,class: "center-block" %>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
					<%= f.submit "投稿する", class: "btn btn-primary" %>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</span>

app/views/posts/edit.html.erb
<div class="container-fluid"> 
  <div class="row">
    <div class="col-md-8 col-md-offset-2 text-center">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">編集</h3>
        </div>
        <div class="panel-body">
          <%= form_for(@post) do |f| %>
          <p>タイトル</p>
          <%= f.text_field :post_title, size: "70x1" %>
          <p>テキスト</p>
          <%= f.text_area :post_text, :size => "70x8" %>
          <p>画像</p>
          <%= f.attachment_field :post_image,class:"center-block" %>
          <%= f.submit "更新する",class: "btn btn-primary " %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container-fluid">
  <% if flash[:notice] %>
  <p id="flash"> <%= flash[:notice] %></p>
  <% end %>
  <div class="raw">
    <div class="col-md-8 col-md-offset-2">
      <% @search_posts.each do |post| %>
      <div class="well" id="contentsbox">
        <%= attachment_image_tag post.user, :user_image, :fill, 70, 70 %>
        <span class="notspillout">
          <strong style="margin-left:15px"><%= link_to post.post_title,post_path(post.id) %></strong>
          <div id="repfav">
            <% if current_user.admin? %>
            <%= link_to "delete", post_path(post.id), method: :delete, data: {confirm: "消去しますか?"}, class: "btn btn-danger" %>
            <% end %>
            <i class="fas fa-reply"></i> <%= post.replies.count %>
            <i class="fas fa-heart"></i> <%= post.favorites.count %>
            by <%= link_to post.user.name, user_path(post.user.id) %>
            <%= post.created_at.strftime('%Y/%m/%d %H:%M') %> ( <%= time_ago_in_words(post.created_at) %> ago )
          </div>
        </span>
      </div>
      <% end %>
    </div>
    <div class="col-md-2">
      <!-- modal -->
      <%= render 'posts/postmodal', post: @post %>
      <!-- /modal -->
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container-fluid"> 
	<% if flash[:notice] %>
	<p id="flash"> <%= flash[:notice] %></p>
	<% end %>
	<div class="raw">
		<div class="col-md-10 col-md-offset-1 notspillout">
			<h2 class="text-center" style="color:#ffffff;"><%= @post.post_title %></h2>		
		</div>
		<div class="col-md-1" id="headbutton">
			<!--modal-->
			<%= render 'posts/replymodal', post: @post, reply: @reply %>
			<!--/modal-->
			<%= link_to 'ツイート', "https://twitter.com/share?url=#{request.url}&text=#{@post.post_title}", title: 'Twitter', target: '_blank',class: "btn btn-primary fab fa-twitter" %>
			<!--fav-->
			<% if @post.favorited_by?(current_user) %>
			<%= link_to post_favorites_path(@post), method: :delete do %>
			<button type="button" class="btn btn-danger btn-sm"><i class="fa fa-heart" aria-hidden="true"><%= @post.favorites.count %> いいね!</i></button>
			<% end %>
			<% else %>
			<%= link_to post_favorites_path(@post), method: :post do %>
			<button type="button" class="btn btn-info btn-sm"><i class="fa fa-heart" aria-hidden="true"></i><%= @post.favorites.count %> いいね!</i></button>
			<% end %>
			<% end %>
			<!--/fav-->
		</div>
		<% @replies.each do |reply| %>
		<% if @post.user != reply.user %>
		<!--other_user_reply-->
		<div class="col-md-10 col-md-offset-1" id="contentsbox">
			<div class="col-md-5 well">
				<div class="notspillout">
					<p id="posttitle"><%= reply.reply_title %></p>
					<%= attachment_image_tag reply, :reply_image, :fill, 436, 436 %>
					<p id="posttext"><%= reply.reply_text %></p>
					<%= link_to user_path(reply.user.id) do %>
					<%= attachment_image_tag reply.user, :user_image, :fill, 50, 50 %>
					<% end %>
					<%= link_to reply.user.name,user_path(reply.user.id) %>
					<p class="text-right"><%= reply.created_at.strftime('%Y/%m/%d %H:%M') %> ( <%= time_ago_in_words(reply.created_at) %> ago )</p>
				</div>
			</div>
		</div>
		<!--/other_user_reply-->
		<% else %>
		<!--@post.user_reply-->
		<div class="col-md-10 col-md-offset-1" id="contentsbox">
			<div class="col-md-5 col-md-offset-7 well">
				<div class="notspillout">
					<p id="posttitle"><%= reply.reply_title %></p>
					<%= attachment_image_tag reply, :reply_image, :fill, 436, 436 %>
					<p id="posttext"><%= reply.reply_text %></p>
					<%= link_to user_path(reply.user.id) do %>
					<%= attachment_image_tag reply.user, :user_image, :fill, 50, 50 %>
					<% end %>
					<%= link_to reply.user.name, user_path(reply.user.id)%>
					<p class="text-right"><%= reply.created_at.strftime('%Y/%m/%d %H:%M') %> ( <%= time_ago_in_words(reply.created_at) %> ago )</p>
				</div>
			</div>
		</div>
		<!--/@post.user_reply-->
		<% end %>
		<% end %>
		<!--first_post-->
		<div class="col-md-10 col-md-offset-1" id="contentsbox">
			<div class="col-md-5 col-md-offset-7 well">
				<div class="notspillout">
					<p id="posttitle"><%= @post.post_title %></p>
					<div class="notspillout">
						<span class="btn btn-default"><%= raw(@post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')) %></span>
					</div>
					<%= attachment_image_tag @post, :post_image, :fill, 436, 436 %>
					<p id="posttext"><%= @post.post_text %></p>
					<div>
						<%= link_to user_path(@post.user.id) do %>
						<%= attachment_image_tag @post.user, :user_image, :fill, 50, 50 %>
						<% end %>
						<%= link_to @post.user.name, user_path(@post.user.id)%>
					</div>
					<div class="pull-right">
						<% if current_user.admin? || current_user == @post.user %>
						<span class="button">
							<%= link_to "edit",edit_post_path(@post.id), class: "btn-sm btn-warning" %>
							<%= link_to "delete", post_path(@post.id), method: :delete, data: {confirm: "消去しますか?"}, class: "btn-sm btn-danger" %>
						</span>
						<% end %>
						<span><%= @post.created_at.strftime('%Y/%m/%d %H:%M') %> ( <%= time_ago_in_words(@post.created_at) %> ago )</span>
					</div>
				</div>
			</div>
		</div>
		<!--/first_post-->
	</div>
</div>
<div class="container-fluid">
	<div class="raw">
		<div class="col-md-10 col-md-offset-1">
			<!--comment-->
			<% @post.comments.each do |comment| %>
			<div class="well commentform">
				<%= link_to user_path(comment.user.id) do %>
				<%= attachment_image_tag comment.user, :user_image, :fill, 40, 40 %>
				<% end %>
				<%= comment.comment_text %>
				<p class="text-right">
					by <%= link_to comment.user.name,user_path(comment.user.id) %>
					<%= comment.created_at.strftime('%Y/%m/%d %H:%M') %> ( <%= time_ago_in_words(comment.created_at) %> ago )
				</p>
			</div>
			<% end %>
			<%= form_for [@post, @comment] do |f| %>
			<%= f.text_area :comment_text, rows:'1', class: "form-control commentform",placeholder: "コメントをここに" %>
			<%= f.submit "コメントを投稿", class: "btn btn-default center-block" %>
			<% end %>
			<!--/comment-->
		</div>
	</div>
</div>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="container-fluid"> 
	<div class="row">
		<div class="col-md-6 col-md-offset-3 text-center">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h5 class="panel-title">ユーザー情報編集</h5>
				</div>
				<div class="panel-body">
					<%= form_for(@user) do |f| %>
					<div class="field">
						<%= f.text_field :name, placeholder:"名前", size: "35x1" %>
					</div>
					<div class="field">
						<%= f.text_area :profile, placeholder:"自己紹介", size: "70x4" %>
					</div>
					<%= f.attachment_field :user_image,class: "center-block" %>
					<%= f.submit "保存",class: "btn btn-primary" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container-fluid">
	<div class="raw">
		<div class="col-md-8 col-md-offset-2">
			<% @users.each do |user| %>
			<div class="well" id="contentsbox">
				<%= link_to attachment_image_tag(user, :user_image, :fill, 70, 70),user_path(user.id) %>
				<div class="inline-block notspillout" style="margin-left: 15px;">
					<p><strong><%= link_to user.name,user_path(user.id) %></strong></p>
					<%= user.profile %>
				</div>
				<div id="repfav">
					<i class="fas fa-tree"></i> <%= user.posts.count %>
					<i class="fas fa-reply-all"></i> <%= user.replies.count %>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
	<% if flash[:notice] %>
	<p id="flash"> <%= flash[:notice] %></p>
	<% end %>
	<div class="raw">
		<div class="col-md-3 col-md-offset-1 well" id="scrollbox">
			<% @user ||= current_user %>
			<!--follow status -->
			<h4><%= @user.following.count %> Following</h4>
			<% @following.each do |user| %>
			<div class="inline-block" id="follow">
				<%= link_to user_path(user.id) do %>
				<%= attachment_image_tag user, :user_image, :fill, 40, 40 %>
				<% end %> 
			</div>
			<% end %>
			<h4><%= @user.followers.count %> Followers</h4>
			<% @followers.each do |user| %>
			<div class="inline-block" id="follow">
				<%= link_to user_path(user.id) do %>
				<%= attachment_image_tag user, :user_image, :fill, 40, 40 %>
				<% end %>
			</div>
			<% end %>
			<!-- /follow status -->
		</div>
		<div class="col-md-4 well" id="scrollbox">
			<h4><%= @user.posts.count %> 件の投稿</h4>
			<% @posts.each do |post| %>
			<ul class="list-group">
				<li class="list-group-item">
					<%= link_to post.post_title, post_path(post.id) %>
					<p class="text-right">
						<i class="fas fa-reply"></i> <%= post.replies.count %>
						<i class="fas fa-comment"></i> <%= post.comments.count %>
						<i class="fas fa-heart"></i> <%= post.favorites.count %>
					</p>
				</li>
			</ul>
			<% end %>
			<h4><%= @user.replies.count %> 件の返信</h4>
			<% @replies.each do |reply| %>
			<ul class="list-group">
				<li class="list-group-item">
					<%= link_to reply.post.post_title,post_path(reply.post.id) %>
					<p class="text-right">
						<i class="fas fa-reply"></i> <%= reply.post.replies.count %>
						<i class="fas fa-comment"></i> <%= reply.post.comments.count %>
						<i class="fas fa-heart"></i> <%= reply.post.favorites.count %>
					</p>
				</li>
			</ul>
			<% end %>
		</div>
		<div class="col-md-3 well notspillout" id="scrollbox">
			<%= attachment_image_tag @user, :user_image, :fill, 320, 320, class: "img-responsive center-block" %>
			<h4><%= @user.name %></h4>
			<p><%= @user.profile %></p>
			<p>登録日 : <%= @user.created_at.strftime('%Y/%m/%d %H:%M') %> ( <%= time_ago_in_words(@user.created_at) %> ago )</p>
			<% if current_user.admin? || current_user == @user %>
			<p class="text-right"><%= link_to "edit",edit_user_path(current_user.id), class: "btn btn-warning btn-block" %></p>
			<% end %>
			<!--follow_unfollow botton-->
			<% if current_user != @user %> 
			<div id="follow_form">
				<% unless current_user.following?(@user) %>
				<%= form_for(current_user.active_relationships.build) do |f| %>
				<div><%= hidden_field_tag :followed_id, @user.id %></div>
				<%= f.submit "Follow", class: "btn btn-primary btn-block" %>
				<% end %>
				<% else %>
				<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
				html: { method: :delete }) do |f| %>
				<%= f.submit "Unfollow", class: "btn btn-default btn-block" %>
				<% end %>
				<% end %>
			</div>
			<div id="followers">
				<% unless current_user.followers?(@user) %>
				<p class="text-right">
					このユーザーにフォローされていません
					<% else %>
					このユーザーにフォローされています
				</p>
				<% end %>
			</div>
			<% end %>
			<!--/follow_unfollow botton-->
		</div>
	</div>
</div>

<style>
	.well {
		right: 5px;
	}
</style>